Update obs-plugintemplate to match changes on obs-studio master (#27)
Update macOS build scripts

* Update buildspec.json to support multiple Qt versions and different
  requested Qt versions per platform
* Add generator command line switch for CMake generator selection
* Add automatic multi processing support to GNU Makefile generator
* Add skip command line switch to manually speed up consecutive runs
* Fix zsh scoping issues
* Add support for CMake debug output if debug switch is supplied
* Extract pre-built dependencies into more specifically named directory
* Update notarization process to use updated xcrun functionality (macOS)
* Increase required development version to macOS 11.0

 CI: Update Linux build scripts

* Adds support for "Aptfile"-based installation of build requirements
* Adds support for Qt6 dependencies installed via apt-get

cmake: Update plugin helper to support Qt6 and proper macOS targets

* Also changes name of packages project file to use lowercase "macos" to
avoid issues with case-sensitive file systems.

CI: Update Windows build scripts

* Add switches to skip dependency download or extraction, and building
* Add support for updated buildspec.json
* Update Expand-ArchiveExt with most current version from ops-deps
* Update Invoke-GitCheckout with most current version from obs-deps
* Update Setup-Host to use loop-based processing and support updated
  buildspec.json format and support skip switches
* Update Setup-Obs to use values from buildspec.json file and support
  skip switches

CI: Update Ubuntu image to 22 for clang-format-13 support

* buildspec: Update obs-studio to 28.0.0-beta1 tag

diff --git a/.github/scripts/utils.zsh/check_macos b/.github/scripts/utils.zsh/check_macos
--- a/.github/scripts/utils.zsh/check_macos
+++ b/.github/scripts/utils.zsh/check_macos
@@ -3,8 +3,8 @@ autoload -Uz is-at-least log_info log_error log_status read_codesign
 local macos_version=$(sw_vers -productVersion)
 
 log_info 'Checking macOS version...'
-if ! is-at-least 10.15.0 "${macos_version}"; then
-  log_error "Minimum required macOS version is 10.15, but running on macOS ${macos_version}"
+if ! is-at-least 11.0 "${macos_version}"; then
+  log_error "Minimum required macOS version is 11.0, but running on macOS ${macos_version}"
   return 2
 else
   log_status "macOS ${macos_version} is recent"
@@ -16,5 +16,5 @@ if (( ! ${+commands[brew]} )) {
   return 2
 }
 
-brew bundle --file "${SCRIPT_HOME}/.Brewfile" --no-upgrade
+brew bundle --file "${SCRIPT_HOME}/.Brewfile"
 rehash
